
name: Theme Review 

on: repository_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Download Theme
      run: |
        curl -L -o theme.zip "${{ github.event.client_payload.theme_zip }}"
        unzip theme.zip

    - uses: actions/setup-node@v1
      with:
        node-version: '12'  
    
    - name: Test My Theme
      id: test
      uses: StevenDufresne/theme-review-action@fix_github
      with:
        root-folder: ${{ github.event.client_payload.theme_slug }}
        accessible-ready: ${{ github.event.client_payload.accessible_ready }}
        ui-debug: true  
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Screenshots
        path: ${{ steps.test.outputs.screenshots }}
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Logs
        path: ${{ steps.test.outputs.logs }}
