name: Theme Review 

on: repository_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Download Theme
      run: |
        curl -L -o theme.zip "${{ github.event.client_payload.theme_zip }}"
        unzip theme.zip
    - name: Print Environment
      env:
          GITHUB_EVENT: ${{ toJSON(github.event.client_payload) }}
      run: echo "$GITHUB_EVENT"
    - name: Test My Theme
      id: test
      uses: WordPress/theme-review-action@try/use-a-reporter
      with:
        root-folder: ${{ github.event.client_payload.theme_slug }}
        accessible-ready: ${{ github.event.client_payload.accessible_ready }}
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Ui-check output
        path: ${{ steps.test.outputs.ui-check-output }}
        retention-days: 5
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Logs
        path: ${{ steps.test.outputs.logs }}      
    - name: Post UI Errors
      if: ${{ always() }}
      run: |
        curl --request POST \
          --url 'https://webhook.site/6fc8195a-922a-4708-9b2c-1c7f67736eaa' \
          --data-binary "content=@${{ steps.test.outputs.logs }}/ui-check-errors.txt"

